version: "2"
services:
  rabbitmq:
    image: rabbitmq:3.6.6-management
    expose:
      - 5672
      - 15672
      - 25672
    environment:
      LK_RANCHER_SERVICE_DISCOVERY: true
      RABBITMQ_DEFAULT_USER: "${username}"
      RABBITMQ_DEFAULT_PASS: "${password}"
      RABBITMQ_DEFAULT_VHOST: "/${vhost}"
    labels:
      io.rancher.container.hostname_override: container_name
