version: "2"
services:
  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - 5672:5672/tcp
      - 15672:15672/tcp
      - 25672:25672/tcp
    environment:
      LK_RANCHER_SERVICE_DISCOVERY: true
      RABBITMQ_DEFAULT_USER: "${username}"
      RABBITMQ_DEFAULT_PASS: "${password}"
      RABBITMQ_DEFAULT_VHOST: "/${vhost}"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
